source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.2'

target 'ALKO' do
end

[
  'RSKImageCropper',
  'QBImagePickerController',
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end
